apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-pyagent
  labels:
    app: appd-bankofanthos
data:
  pyagent.sh : |
    #! /bin/sh
    echo "creating file"
    if echo "$HOSTNAME" | grep -q "tuning"
    then
        HOSTNAME=$HOSTNAME
    else
        HOSTNAME=frontend
    fi
    cat >/appdynamics/appd.cfg <<EOL
    [agent]
    app = ${APPDYNAMICS_AGENT_APPLICATION_NAME}
    tier = frontend-service
    node = ${HOSTNAME}

    [log]
    level = debug
    debugging = on

    [controller]
    host = ${APPDYNAMICS_CONTROLLER_HOST_NAME}
    port = 443
    ssl = on
    account = ${APPDYNAMICS_AGENT_ACCOUNT_NAME}
    accesskey = ${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    EOL
    cat /appdynamics/appd.cfg