
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice
spec:
  maxReplicas: 15
  minReplicas: 3
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
